spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      properties:
        hibernate:
          format_sql: true
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "jeonghj@devfox.co.jp"
    password: "kgas uoaa ngng nxhe"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


sql:
  init:
    mode: always

server:
  port: 8080